services:
  - type: web
    name: deepfake-sentinel-api
    runtime: python
    rootDir: backend
    buildCommand: |
      pip install -r requirement.txt
      python preload_models.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0